/* Write your PL/SQL query statement below */
-- SELECT NAME AS EMPLOYEE FROM EMPLOYEE E WHERE E.SALARY > (SELECT SALARY FROM EMPLOYEE WHERE ID=E.MANAGERID);

-- ALTERNATIVE
SELECT E2.NAME AS EMPLOYEE FROM EMPLOYEE E1 INNER JOIN EMPLOYEE E2 ON E1.ID = E2.MANAGERID WHERE E1.SALARY < E2.SALARY;